FROM ubuntu:18.04 as build
RUN apt update && apt install git default-jdk maven wget -y
WORKDIR /App42PaaS
RUN git clone https://github.com/shephertz/App42PaaS-Java-MySQL-Sample.git
WORKDIR /App42PaaS/App42PaaS-Java-MySQL-Sample
RUN mvn package
