FROM ubuntu:18.04
RUN apt update && apt install git default-jdk maven -y
WORKDIR /App42PaaS
RUN git clone https://github.com/shephertz/App42PaaS-Java-MySQL-Sample.git
WORKDIR /App42PaaS/App42PaaS-Java-MySQL-Sample
RUN mvn package
RUN mkdir data config && cp target/*.war data
COPY Config.properties config
RUN cp -r /App42PaaS/App42PaaS-Java-MySQL-Sample/WebContent config
