---
version: '3'

services:

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: base
    ports:
      - "3300:3306"
    volumes:
      - db:/var/lib/mysql

  building:
    build:
      context: .
      dockerfile: Dockerfile.maven
    volumes:
      - web_data:/App42PaaS/App42PaaS-Java-MySQL-Sample/target/

  prod:
    depends_on:
      - database
      - building
    build:
      context: .
      dockerfile: Dockerfile.tomcat
    ports:
      - "8081:8080"
    volumes:
      - web_data:/usr/local/tomcat/webapps/

volumes:
  db:
  web_data:
